### ISSUE TITLE
next post

### ISSUE THREAD

**Issue by d1a0** [xbclub/Hexo-theme-sakura#1]
next post那里的图片，一直是bilibili小电视

**Comment by xbclub** [comment]
我电脑凉凉了，等我电脑好了就修。

**Comment by 1134451886** [comment]
new post会自动写入honjun作者每次要自己修改，表格没有样式和边框，我在style.css里设置样式的话又会导致代码块也包含表格样式……

**Comment by xbclub** [comment]
> new post会自动编写honjun作者每次都要自己修改，表格没有样式和边框，我在style.css里设置样式的话又会导致代码块也包含表格样式……

通过hexo命令来创建的新文章?

**Comment by 1134451886** [comment]
> 
> 
> > new post会自动编写honjun作者每次都要自己修改，表格没有样式和边框，我在style.css里设置样式的话又会导致代码块也包含表格样式……
> 
> 通过hexo命令来创建的新文章?

是的

**Comment by 1134451886** [comment]
还有，复制内容时会加上出处信息，这个有开关可以关掉吗？复制很短的代码都会加上这个

**Comment by xbclub** [comment]
> 还有，复制内容时会加上出处信息，这个有开关可以关掉吗？复制很短的代码都会加上这个

你新建一个issue来说明问题，这个issue跟你的问题不一样。

**Comment by xbclub** [comment]
已修复
