### ISSUE TITLE
hexo new post新建会自动写入author: honjun等信息……

### ISSUE THREAD

**Issue by 1134451886** [xbclub/Hexo-theme-sakura#2]
希望可以自动写入自己设定的作者信息，比如自己叫AS，就写入author: AS……
![](https://r.photo.store.qq.com/psc?/V14RBB4W1HO62x/iXs1ae7hmJtTd.wIcSd4.TP0onj0cMqdpNN00XspqMRZMBaO*1xotxyZcmsB0mgKZw9vHcc4JWomX7AdXuWUqD40HEvQjeqpHF4W05h3iOE!/r)

**Comment by xbclub** [comment]
ok。

**Comment by xbclub** [comment]
请重新使用hexo init 生成新的hexo博客 新的sakura使用方法 [参考此文章](https://docs.42cloud.cn/sakura/#/home?id=%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85)
